---
title: "11장 정규모집단에서의 추론"
author: "Taeyoon Kim"
date: "2024-08-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

### 11.2 t 분포

<br/>

#### 11.2.4 t 분포를 이용하여 각 경우의 확률을 구하라.

##### (1) 자유도가 17일 때, $t < -1.740$ 일 확률

##### (2) 자유도가 6일 때, $|t| < 3.143$ 일 확률 

##### (3) 자유도가 18일 때, $-1.330 < t < 1.330$ 일 확률

##### (4) 자유도가 10일 때, $-1.372 < t < 2.764$ 일 확률


```{r}
# pt: 누적분포함수, dt: pdf, qt: 누적분포함수의 역함수, rt: 임의추출
answer_1 = pt(-1.740, 17)
answer_2 = (pt(3.143, 6) - 0.5) * 2
answer_3 = (pt(1.330, 18) - 0.5) * 2
answer_4 = 0.5 - pt(-1.372, 10) + pt(2.764, 10) - 0.5

cat("(1)", answer_1, "\n(2)", answer_2, "\n(3)", answer_3, "\n(4)", answer_4)
```

<br/>

#### 11.2.6 자유도가 5, 10, 15, 20, 29일 때, $t_0.05$값을 찾아라. 이 값이 자유도에 따라 증가하는가? 아니면 감소하는가?

```{r}
cat(   # 주의! 상위 0.05를 찾는 것이므로 누적 0.95의 역함수로 찾아야 함
  qt(p=0.95, df=5),
  qt(p=0.95, df=10),
  qt(p=0.95, df=15),
  qt(p=0.95, df=20),
  qt(p=0.95, df=29),
  sep='    '
)
cat("\n이 값은 자유도에 따라 감소한다.")
```

<br/>

#### 11.2.8 다음의 각 경우를 만족하는 $c$값을 추측하라.

##### (1) 자유도가 5일 때, $P[t>c]=0.03$

##### (2) 자유도가 9일 때, $P[t>c]=0.016$

##### (3) 자유도가 12일 때, $P[t<c]=0.004$

##### (4) 자유도가 5일 때, $P[|t|>c]=0.03$

##### (5) 자유도가 21일 때, $P[|t|<c]=0.96$

```{r}
answer_1 = qt(p=1-0.03, df=5)
answer_2 = qt(p=1-0.016, df=9)
answer_3 = qt(p=0.004, df=12)
answer_4 = qt(p=1-0.03/2, df=5)
answer_5 = qt(p=0.98, df=21)

cat("(1)", answer_1, "\n(2)", answer_2, 
    "\n(3)", answer_3, "\n(4)", answer_4, "\n(5)", answer_5)
```




