---
title: "10장 통계적 추론"
author: "Taeyoon Kim"
date: "2024-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

### 10.2 모평균의 추정(표본의 크기가 클 때)

<br/>

#### 10.2.2 표본의 크기 $n=48$, 표본평균 $\bar{x}=86.5$, 표본표준편차 $s=7.9$라고 할 때 모평균 $\mu$의 90% 신뢰구간을 구하라.

```{r}
n=48
x_bar=86.5
s=7.9

lowerbound = x_bar + qnorm(0.05) * s / sqrt(n)
upperbound = x_bar + qnorm(0.95) * s / sqrt(n)

cat("(", lowerbound, ",", upperbound, ")")
```

<br/>

#### 10.2.4 한 연구자가 모평균의 90% 신뢰구간을 구한다고 하자. 그러한 작업을 200번 하였다고 하면 몇 개의 신뢰구간이 실제의 평균을 포함하고 있겠는가?

180개  
신뢰구간은 추정량의 분포를 이용하여 표본으로부터 모수 값을 포함하리라고 예상되는 구간을 구하여 제시하는 것이다.

<br/>

#### 10.2.6 한 자동차 공장에서 38명의 새로운 직원들이 2주 동안의 연수를 마친 후, 특정한 작업을 얼마나 빠른 시간 안에 해 내는지를 측정하였다. 그 작업을 끝내는 데 걸리는 시간의 평균과 표준편차가 각각 68초와 12초였다. 모든 직원들이 2주의 교육을 마쳤을 때 그 작업을 마치는 데 걸리는 시간의 평균값의 95% 신뢰구간을 구하라.

```{r}
n=38
x_bar=68
s=12

lowerbound = x_bar + qnorm(0.025) * s / sqrt(n)
upperbound = x_bar + qnorm(0.975) * s / sqrt(n)

cat("(", lowerbound, ",", upperbound, ")")
```

<br/>

#### 10.2.8



